<a href="https://colab.research.google.com/github/aaron-fonseca/aaron-fonseca/blob/main/NLP_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import nltk
import warnings

%matplotlib inline    

warnings.filterwarnings('ignore')

In [3]:

dataset = pd.read_csv('/content/Youtube04-Eminem.csv')
dataset

COMMENT_ID  \
0              z12rwfnyyrbsefonb232i5ehdxzkjzjs2   
1            z130wpnwwnyuetxcn23xf5k5ynmkdpjrj04   
2              z13vsfqirtavjvu0t22ezrgzyorwxhpf3   
3            z12wjzc4eprnvja4304cgbbizuved35wxcs   
4              z13xjfr42z3uxdz2223gx5rrzs3dt5hna   
..                                           ...   
443  LneaDw26bFu3RCmyrWyP9S6wh1h9dBv3X95g1HzKAb4   
444  LneaDw26bFsD65dtIvAEObWYIYnFTqQDKBek_Ypz3J8   
445  LneaDw26bFuvs-8oWkLpAFa6g3QHpWD8k7sbbMP3Bg8   
446        z12hfp2wmyuqztkw504cgblyxtbsxjuzeow0k   
447          z13tsbc5vvn0hdozz04chjt51lq1cvris0k   

                             AUTHOR                        DATE  \
0                       Lisa Wellas                         NaN   
1                      jason graham  2015-05-29T02:26:10.652000   
2                        Ajkal Khan                         NaN   
3                     Dakota Taylor  2015-05-29T02:13:07.810000   
4                       Jihad Naser                         NaN   
..                              ...                         ...   
443                         Dany PK                         NaN   
444               SmexyFriedChicken                         NaN   
445  The Guy That's Done Everything                         NaN   
446                   Jesse Pinkman  2015-05-06T11:42:44.601000   
447                   Gaming Gaming  2015-05-06T10:56:35.972000   

                                               CONTENT  CLASS  
0            +447935454150 lovely girl talk to me xxx      1  
1      I always end up coming back to this song<br />      0  
2    my sister just received over 6,500 new <a rel=...      1  
3                                                Cool      0  
4                       Hello I&#39;am from Palastine      1  
..                                                 ...    ...  
443           SUBSCRIBE TO MY CHANNEL X PLEASE!. SPARE      1  
444  Check out my videos guy! :) Hope you guys had ...      1  
445  3 yrs ago I had a health scare but thankfully ...      1  
446       Rihanna looks so beautiful with red hair ;)      0  
447  857.482.940 views AWESOME !!!!!!!!!!!!!!!!!!!!...      0  

[448 rows x 5 columns]

In [7]:
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [5]:
def tokenize(comment):
    return word_tokenize(comment)

In [8]:
dataset['tokens'] = dataset['CONTENT'].apply(tokenize)

In [9]:
print('Tokens for first comment:')
print(dataset['tokens'][0])

Tokens for first comment:
['+447935454150', 'lovely', 'girl', 'talk', 'to', 'me', 'xxx\ufeff']


In [10]:
from nltk.stem import SnowballStemmer
def stem(comment):
    stemmer = SnowballStemmer('english')
    return [stemmer.stem(word) for word in word_tokenize(comment)]

# Apply the stemming function to each comment in the dataset
dataset['stemmed'] = dataset['CONTENT'].apply(stem)

# Print the stemmed words for the first comment in the dataset
print('Stemmed words for Third comment:')
print(dataset['stemmed'][2])

Stemmed words for Third comment:
['my', 'sister', 'just', 'receiv', 'over', '6,500', 'new', '<', 'a', 'rel=', "''", 'nofollow', "''", 'class=', "''", 'ot-hashtag', "''", 'href=', "''", 'https', ':', '//plus.google.com/s/', '%', '23activ', "''", '>', '#', 'activ', '<', '/a', '>', 'youtub', 'view', 'right', 'now', '.', 'the', 'onli', 'thing', 'she', 'use', 'was', 'pimpmyview', '.', 'com\ufeff']


In [12]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
def lemmatize(comment):
    lemmatizer = WordNetLemmatizer()
    return [lemmatizer.lemmatize(word, pos='v') for word in word_tokenize(comment)]

# Apply the lemmatization function to each comment in the dataset
dataset['lemmatized'] = dataset['CONTENT'].apply(lemmatize)

# Print the lemmatized words for the first comment in the dataset
print('Lemmatized words for Third comment:')
print(dataset['lemmatized'][2])

[nltk_data] Downloading package wordnet to /root/nltk_data...


Lemmatized words for Third comment:
['my', 'sister', 'just', 'receive', 'over', '6,500', 'new', '<', 'a', 'rel=', "''", 'nofollow', "''", 'class=', "''", 'ot-hashtag', "''", 'href=', "''", 'https', ':', '//plus.google.com/s/', '%', '23active', "''", '>', '#', 'active', '<', '/a', '>', 'youtube', 'view', 'Right', 'now', '.', 'The', 'only', 'thing', 'she', 'use', 'be', 'pimpmyviews', '.', 'com\ufeff']


In [13]:
new_dataset = dataset[['CONTENT', 'CLASS']]
new_dataset

CONTENT  CLASS
0            +447935454150 lovely girl talk to me xxx      1
1      I always end up coming back to this song<br />      0
2    my sister just received over 6,500 new <a rel=...      1
3                                                Cool      0
4                       Hello I&#39;am from Palastine      1
..                                                 ...    ...
443           SUBSCRIBE TO MY CHANNEL X PLEASE!. SPARE      1
444  Check out my videos guy! :) Hope you guys had ...      1
445  3 yrs ago I had a health scare but thankfully ...      1
446       Rihanna looks so beautiful with red hair ;)      0
447  857.482.940 views AWESOME !!!!!!!!!!!!!!!!!!!!...      0

[448 rows x 2 columns]

In [14]:
import re

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [15]:
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for word in r:
        input_txt = re.sub(word, "", input_txt)
    return input_txt

In [16]:
new_dataset['CONTENT'] = np.vectorize(remove_pattern)(new_dataset['CONTENT'], "@[\w]*")

In [17]:
new_dataset['CONTENT'] = new_dataset['CONTENT'].str.replace("[^a-zA-Z#]", " ")
new_dataset.head()

CONTENT  CLASS
0                        lovely girl talk to me xxx       1
1    I always end up coming back to this song br          0
2  my sister just received over       new  a rel ...      1
3                                              Cool       0
4                     Hello I #   am from Palastine       1

In [18]:
new_dataset['CONTENT'] = new_dataset['CONTENT'].apply(lambda x: " ".join([w for w in x.split() if len(w)>3]))
new_dataset.head()

CONTENT  CLASS
0                                   lovely girl talk      1
1                       always coming back this song      0
2  sister just received over nofollow class hasht...      1
3                                               Cool      0
4                               Hello from Palastine      1

In [20]:
new_dataset['CONTENT'] = new_dataset['CONTENT'].apply(lambda x: x.lower())
new_dataset

CONTENT  CLASS
0                                     lovely girl talk      1
1                         always coming back this song      0
2    sister just received over nofollow class hasht...      1
3                                                 cool      0
4                                 hello from palastine      1
..                                                 ...    ...
443                     subscribe channel please spare      1
444                  check videos hope guys good laugh      1
445  health scare thankfully okay realized wasn liv...      1
446                  rihanna looks beautiful with hair      0
447                                      views awesome      0

[448 rows x 2 columns]

In [21]:
nltk.download('all')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid=SentimentIntensityAnalyzer()

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

In [22]:
from textblob import TextBlob

def get_sentiment(comment):
    blob = TextBlob(comment)
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return 'positive'
    elif polarity < 0:
        return 'negative'
    else:
        return 'neutral'


dataset['sentiment'] = dataset['CONTENT'].apply(get_sentiment)

sentiment_counts=print(dataset['sentiment'].value_counts())


positive    232
neutral     185
negative     31
Name: sentiment, dtype: int64


In [23]:
print('\nSample comments by sentiment:')
for sentiment in ['positive', 'negative', 'neutral']:
    sample = dataset[dataset['sentiment'] == sentiment]['CONTENT'].sample(5, random_state=1)
    print(f'{sentiment.capitalize()} comments:\n{sample}\n')


Sample comments by sentiment:
Positive comments:
440    DO YOU KNOW HOW SEAN KINGSTON GOT FAMOUS WHY D...
181    You guys should check out this EXTRAORDINARY w...
343    I&#39;m subscribing to you just because your c...
153    You guys should check out this EXTRAORDINARY w...
224          Check out my channel im 15 year old rapper!
Name: CONTENT, dtype: object

Negative comments:
399    Usually guys I would vote people like this dow...
70     please read this please! i am a country singer...
213    I cried this song bringing back some hard memo...
272                                          i hate rap
257    i been working so hard for the past 60 days to...
Name: CONTENT, dtype: object

Neutral comments:
33                  Check out this playlist on YouTube:
425                              is that megan fox x:D?
150    do you guys know, there&#39;s a part two of th...
77                     Is that Charlie from lost?<br />
400                                              ❤️❤️❤️

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1420)

In [25]:
X = cv.fit_transform(new_dataset['CONTENT']).toarray()
y = dataset.iloc[:, -1].values

In [26]:
import pickle
bow_path = 'c1_BoW_Sentiment_Model.pkl'
pickle.dump(cv, open(bow_path, "wb"))

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [31]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [32]:
import joblib
joblib.dump(classifier, 'c2_Classifier_Sentiment_Model') 
     

['c2_Classifier_Sentiment_Model']

In [33]:
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
matrx = confusion_matrix(y_test, y_pred)
print(matrx)

accuracy_score(y_test, y_pred)

[[ 2  1  6]
 [10 12 17]
 [ 7  4 31]]


0.5